version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing to push artifact to GitHub...
      # Configurar nombre y correo para Git
      - git config --global user.name "chca115"
      - git config --global user.email "cclaro@3htp.com"
      # Clonar el repositorio de origen para poder hacer commits
      - git clone https://$GITHUB_TOKEN@github.com/chca115/codebuild-test-aws.git artifact-repo
      - cd artifact-repo
      # Copiar el artefacto generado al repositorio
      - mkdir -p artifacts
      - cp ../target/messageUtil-1.0.jar artifacts/
      # Realizar commit y push al repositorio
      - git add artifacts/messageUtil-1.0.jar
      - git commit -m "Add build artifact, messageUtil-1.0.jar"
      - git push origin main

artifacts:
  files:
    - target/messageUtil-1.0.jar
